enable:
  issues: false
  prs: true

comments:
  prs: |
    Thank you for your efforts!

labels:
  'bug':
    include:
      - '\bfix\b'
  'test':
    include:
      - '\btest\b'
  'feature':
    include:
      - '\bfeat\b'
  'documentation':
    include:
      - '\bdocs\b'
  'refactor':
    include:
      - '\brefactor\b'
  'chore':
    include:
      - '\bchore\b'